import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute,
} from '@tanstack/react-router'
import { TanStackRouterDevtoolsPanel } from '@tanstack/react-router-devtools'
import { TanStackDevtools } from '@tanstack/react-devtools'

import appCss from '../styles.css?url'
import { Header } from '@/routes/-components/header'
import { Provider } from '@/routes/-components/provider'

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { title: 'nkfr26.com' },
      {
        name: 'description',
        content: 'Generated by shadcn/create using TanStack Start',
      },
      { property: 'og:title', content: 'nkfr26.com' },
      {
        property: 'og:description',
        content: 'Generated by shadcn/create using TanStack Start',
      },
      {
        property: 'og:image',
        content: 'https://nkfr26.com/opengraph-image',
      },
      { property: 'twitter:card', content: 'summary_large_image' },
      { property: 'twitter:title', content: 'nkfr26.com' },
      {
        property: 'twitter:description',
        content: 'Generated by shadcn/create using TanStack Start',
      },
      {
        property: 'twitter:image',
        content: 'https://nkfr26.com/opengraph-image',
      },
    ],
    links: [
      { rel: 'stylesheet', href: appCss },
      { rel: 'icon', href: '/icon.png' },
    ],
  }),

  component: RootLayout,
  notFoundComponent: NotFound,
  shellComponent: RootDocument,
})

function RootLayout() {
  return (
    <>
      <Header />
      <Outlet />
    </>
  )
}

function NotFound() {
  return (
    <>
      <div className="grid place-content-center pb-12 select-none">
        <div className="flex items-center">
          <h1 className="mr-5 border-r border-current pr-6 text-2xl">404</h1>
          <h2 className="text-sm">This page could not be found.</h2>
        </div>
      </div>
    </>
  )
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="ja"
      suppressHydrationWarning
      className="[scrollbar-gutter:stable] [text-decoration-skip-ink:none]"
    >
      <head>
        <HeadContent />
      </head>
      <body className="grid min-h-svh grid-rows-[auto_1fr]">
        <Provider>{children}</Provider>
        <TanStackDevtools
          config={{
            position: 'bottom-right',
          }}
          plugins={[
            {
              name: 'Tanstack Router',
              render: <TanStackRouterDevtoolsPanel />,
            },
          ]}
        />
        <Scripts />
      </body>
    </html>
  )
}
