/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpengraphImageIndexRouteImport } from './routes/opengraph-image/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageIndexRoute = OpengraphImageIndexRouteImport.update({
  id: '/opengraph-image/',
  path: '/opengraph-image/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opengraph-image': typeof OpengraphImageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opengraph-image': typeof OpengraphImageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opengraph-image/': typeof OpengraphImageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opengraph-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opengraph-image'
  id: '__root__' | '/' | '/opengraph-image/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpengraphImageIndexRoute: typeof OpengraphImageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image/': {
      id: '/opengraph-image/'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpengraphImageIndexRoute: OpengraphImageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
